"""
Calibration sweep.

For each difficulty 1-10:
  - generate several levels,
  - solve them (exact MCR / solvability / metrics),
  - run Monte Carlo with 4 player policies to get empirical win-rates,
  - aggregate.

Outputs:
  - console table,
  - report.json (full per-difficulty stats),
  - calibrated_constants.json (validated TARGET_MCR + difficulty-index guidance for the TS engine).

Usage:
  python calibrate.py [levels_per_difficulty] [runs_per_policy]
"""

from __future__ import annotations

import json
import os
import random
import sys
import time

import numpy as np

from forge_sim import TARGET_MCR, Level
from generator import generate_level
from policies import win_rate

POLICIES = ["random", "greedy", "lookahead1", "lookahead2"]


def run(levels_per: int = 8, runs_per_policy: int = 120) -> dict:
    rng = random.Random(20260619)
    report = {"generatedAt": time.strftime("%Y-%m-%dT%H:%M:%S"), "difficulties": []}

    print(f"\nKaizen Forge calibration  |  {levels_per} levels/difficulty  x  {runs_per_policy} runs/policy\n")
    header = f"{'D':>2} {'tgtMCR':>7} {'actMCR':>7} {'solv%':>6} {'moves':>6} {'crit':>5} {'bufPk':>6} " + " ".join(f"{p[:6]:>7}" for p in POLICIES)
    print(header)
    print("-" * len(header))

    for D in range(1, 11):
        mcrs, solv, moves, crit, bufpk = [], [], [], [], []
        policy_rates = {p: [] for p in POLICIES}

        for i in range(levels_per):
            print(f"  ..D{D} level {i+1}/{levels_per}", end="\r", flush=True)
            lvl = generate_level(D, seed=rng.randint(0, 2**31 - 1))
            sim = lvl["sim"]
            solvable = bool(sim.get("solvable"))
            solv.append(1.0 if solvable else 0.0)
            if not solvable:
                continue
            if sim.get("mcr") is not None:
                mcrs.append(sim["mcr"])
            if sim.get("total_moves") is not None:
                moves.append(sim["total_moves"])
            if sim.get("critical") is not None:
                crit.append(sim["critical"])
            if sim.get("buffer_peak") is not None:
                bufpk.append(sim["buffer_peak"])

            level_obj = Level(queues=lvl["queues"], customers=lvl["customers"], num_seats=lvl["params"]["numSeats"])
            for p in POLICIES:
                policy_rates[p].append(win_rate(level_obj, p, runs_per_policy, rng))

        act_mcr = float(np.mean(mcrs)) if mcrs else float("nan")
        row = {
            "difficulty": D,
            "targetMCR": TARGET_MCR[D - 1],
            "actualMCR": act_mcr,
            "solvableRate": float(np.mean(solv)) if solv else 0.0,
            "avgMoves": float(np.mean(moves)) if moves else 0.0,
            "avgCritical": float(np.mean(crit)) if crit else 0.0,
            "avgBufferPeak": float(np.mean(bufpk)) if bufpk else 0.0,
            "policyWinRates": {p: (float(np.mean(policy_rates[p])) if policy_rates[p] else 0.0) for p in POLICIES},
        }
        report["difficulties"].append(row)

        rates = " ".join(f"{row['policyWinRates'][p]*100:6.1f}%" for p in POLICIES)
        print(f"{D:>2} {row['targetMCR']:>7.2f} {act_mcr:>7.3f} {row['solvableRate']*100:>5.0f}% "
              f"{row['avgMoves']:>6.1f} {row['avgCritical']:>5.1f} {row['avgBufferPeak']:>6.1f} {rates}    ", flush=True)

    return report


def emit_constants(report: dict, out_dir: str) -> None:
    # Validated target MCR = measured actual MCR per difficulty (what the generator can really hit).
    calibrated = {
        "note": "Auto-generated by tools/forge_lab/calibrate.py. Validated against Monte Carlo.",
        "targetMCR": [round(d["actualMCR"], 3) if d["actualMCR"] == d["actualMCR"] else TARGET_MCR[i]
                      for i, d in enumerate(report["difficulties"])],
        "expectedWinRates": {
            str(d["difficulty"]): {p: round(r, 3) for p, r in d["policyWinRates"].items()}
            for d in report["difficulties"]
        },
        "avgMoves": [round(d["avgMoves"], 1) for d in report["difficulties"]],
        "avgBufferPeak": [round(d["avgBufferPeak"], 2) for d in report["difficulties"]],
    }
    with open(os.path.join(out_dir, "calibrated_constants.json"), "w", encoding="utf-8") as f:
        json.dump(calibrated, f, indent=2)
    with open(os.path.join(out_dir, "report.json"), "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2)


if __name__ == "__main__":
    levels_per = int(sys.argv[1]) if len(sys.argv) > 1 else 8
    runs_per = int(sys.argv[2]) if len(sys.argv) > 2 else 120
    rep = run(levels_per, runs_per)
    out_dir = os.path.dirname(os.path.abspath(__file__))
    emit_constants(rep, out_dir)
    print(f"\nWrote calibrated_constants.json and report.json to {out_dir}\n")
