/**
 * Bakes the 30-level campaign into src/forge/campaignLevels.ts (shipped static data).
 *
 * Run:  npx tsx scripts/buildCampaign.ts
 *
 * Uses the UNCHANGED generator via campaign.buildCampaignLevel (deterministic: fixed
 * seed + empty brain), then prints a validation report comparing each level's measured
 * naive fail-ratio against its tier's target band.
 */

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { CAMPAIGN_SPECS, buildCampaignLevel, tierFailBand } from '../src/forge/campaign';
import type { ForgeLevel } from '../src/forge/types';

const here = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(here, '../src/forge/campaignLevels.ts');

const levels: ForgeLevel[] = [];

console.log('Baking 30 campaign levels (deterministic, empty brain)…\n');
console.log('Lv  Tier         Seats Var Q  Cust Dmd  Items  Moves  NaiveFail  Band        OK   D-idx');
console.log('─'.repeat(96));

for (const spec of CAMPAIGN_SPECS) {
  const t0 = Date.now();
  const level = buildCampaignLevel(spec);
  levels.push(level);

  const sim = level.sim!;
  const items = level.customers.reduce((s, c) => s + c.demand, 0);
  const naive = sim.naiveWinRate ?? 0;
  const fail = 1 - naive;
  const [lo, hi] = tierFailBand(spec.tier);
  const inBand = fail >= lo - 0.05 && fail <= hi + 0.05;
  const ms = Date.now() - t0;

  console.log(
    `${String(spec.level).padStart(2)}  ${spec.tier.padEnd(11)}  ${String(spec.seats).padStart(4)} ` +
      `${String(spec.varieties).padStart(3)} ${String(spec.queues).padStart(2)} ` +
      `${String(spec.customers).padStart(4)} ${String(spec.demand).padStart(3)}  ` +
      `${String(items).padStart(5)}  ${String(sim.totalMoves).padStart(5)}  ` +
      `${(fail * 100).toFixed(0).padStart(7)}%  ` +
      `${`${(lo * 100).toFixed(0)}-${(hi * 100).toFixed(0)}%`.padEnd(10)}  ` +
      `${inBand ? ' ✓ ' : ' · '}  ${sim.difficultyIndex}  (${ms}ms)`,
  );
}

const header = `/**
 * AUTO-GENERATED by scripts/buildCampaign.ts — do not edit by hand.
 * Run \`npx tsx scripts/buildCampaign.ts\` to regenerate.
 *
 * The 30-level hand-tuned campaign (Variant 3). Deterministic & identical for everyone.
 */

import { ForgeLevel } from './types';

export const CAMPAIGN_LEVELS: ForgeLevel[] = `;

writeFileSync(outPath, `${header}${JSON.stringify(levels, null, 2)};\n`, 'utf8');
console.log(`\nWrote ${levels.length} levels to ${outPath}`);
